Repository BroadcomMFD/test4z, pull requests merged in 2022-06, with the labels that each got.

#70 Code improvements and minor fixes before v2.0.0
  README.md
  samples/README.md
  samples/mock/Readme.md
  samples/mock/src/definition.json
  samples/nodejs/README.md
  samples/nodejs/business_cases/check_ordering/checkOrdering.test.ts
  samples/python/src/main/model/diagnostic/DiagnosticModel.py
  samples/python/src/main/utility/CustomAssertions.py
  samples/python/src/test/update/test_update_sample.py
  supportive_cases/ca-view/README.md
Labels: documentation, enhancement

#71 Python - cleanup temp file after script execution
  samples/python/src/main/.scripts/set_mock.py
  samples/python/src/main/.scripts/set_test4z.py
  samples/python/src/main/.scripts/set_zosmf.py
Labels: enhancement

#73 removing the temporary dataset using zowe/files
  samples/nodejs/business_cases/check_ordering/checkOrdering.test.ts
  samples/nodejs/code_snippets/copy.test.ts
Labels: enhancement

#77 Update Readme with mock server
  README.md
Labels: documentation
